import logging
import re
import shlex
import time
from pathlib import PurePosixPath

import docker
import requests
from retailpulse.task_logging import log_execution

from retailpulse.config import (
    FLINK_URL,
    FLINK_CONTAINER,
    MINIO_BUCKET,
)
from retailpulse.health import get_minio_client


RUNNING_STATES = {
    "RUNNING",
    "RESTARTING",
    "CREATED",
    "RECONCILING",
}


def list_flink_jobs() -> list[dict]:
    response = requests.get(
        f"{FLINK_URL}/jobs/overview",
        timeout=15,
    )
    response.raise_for_status()

    return response.json().get("jobs", [])


def find_job_by_name(job_name: str) -> dict | None:
    matches = [
        job
        for job in list_flink_jobs()
        if job.get("name") == job_name
    ]

    if not matches:
        return None

    # Prefer a currently active instance.
    for job in matches:
        if job.get("state") in RUNNING_STATES:
            return job

    return matches[0]


def latest_savepoint(prefix: str) -> str | None:
    """
    Find the newest savepoint directory by locating `_metadata`
    beneath the configured MinIO prefix.
    """
    client = get_minio_client()

    candidates = []

    for obj in client.list_objects(
        MINIO_BUCKET,
        prefix=prefix,
        recursive=True,
    ):
        if obj.object_name.endswith("/_metadata"):
            savepoint_dir = str(
                PurePosixPath(obj.object_name).parent
            )

            candidates.append(
                (
                    obj.last_modified,
                    savepoint_dir,
                )
            )

    if not candidates:
        return None

    candidates.sort(
        key=lambda x: x[0],
        reverse=True,
    )

    _, savepoint_dir = candidates[0]

    return (
        f"s3://{MINIO_BUCKET}/"
        f"{savepoint_dir}"
    )


def _exec_in_jobmanager(command: str) -> str:
    client = docker.from_env()

    container = client.containers.get(
        FLINK_CONTAINER
    )

    result = container.exec_run(
        ["sh", "-lc", command],
        stdout=True,
        stderr=True,
    )

    output = (
        result.output.decode(
            "utf-8",
            errors="replace",
        )
    )

    if result.exit_code != 0:
        raise RuntimeError(
            "Flink command failed.\n"
            f"Command: {command}\n"
            f"Output:\n{output}"
        )

    return output


def submit_flink_job(
    job_path: str,
    job_name: str,
    savepoint_path: str | None = None,
) -> dict:

    # Table/StatementSet jobs otherwise receive an autogenerated name such as
    # "insert-into_...".  Airflow uses the configured name to find an existing
    # job and to inspect its checkpoints, so the submitted pipeline must use
    # that exact name.
    pipeline_name = shlex.quote(
        f"pipeline.name={job_name}"
    )

    if savepoint_path:

        command = (
            "flink run -d "
            f"-D {pipeline_name} "
            f"-s '{savepoint_path}' "
            f"-py '{job_path}'"
        )

    else:

        command = (
            "flink run -d "
            f"-D {pipeline_name} "
            f"-py '{job_path}'"
        )

    log_execution(job_path, FLINK_CONTAINER, command)
    output = _exec_in_jobmanager(
        command
    )

    match = re.search(
        r"JobID\s+([0-9a-fA-F]+)",
        output,
    )

    return {
        "command_output": output,
        "job_id": (
            match.group(1)
            if match
            else None
        ),
        "savepoint": savepoint_path,
    }


def ensure_flink_job(job_config: dict) -> dict:
    log_execution(job_config["path"], FLINK_CONTAINER)
    job_name = job_config["job_name"]

    current = find_job_by_name(
        job_name
    )

    if (
        current
        and current.get("state")
        in RUNNING_STATES
    ):
        return {
            "action": "already_running",
            "job_name": job_name,
            "job_id": current.get("jid"),
            "state": current.get("state"),
        }

    savepoint_path = None

    if job_config.get(
        "restore_from_savepoint",
        False,
    ):
        prefix = job_config.get(
            "savepoint_prefix"
        )

        if prefix:
            savepoint_path = (
                latest_savepoint(prefix)
            )

    submission = submit_flink_job(
        job_config["path"],
        job_name,
        savepoint_path=savepoint_path,
    )

    return {
        "action": (
            "restored_from_savepoint"
            if savepoint_path
            else "started_fresh"
        ),
        "job_name": job_name,
        **submission,
    }


def checkpoint_statistics(
    job_id: str,
) -> dict:
    response = requests.get(
        f"{FLINK_URL}/jobs/{job_id}/checkpoints",
        timeout=15,
    )
    response.raise_for_status()

    data = response.json()

    counts = data.get(
        "counts",
        {}
    )

    return {
        "job_id": job_id,
        "completed": counts.get(
            "completed",
            0,
        ),
        "failed": counts.get(
            "failed",
            0,
        ),
        "in_progress": counts.get(
            "in_progress",
            0,
        ),
        "latest": data.get(
            "latest",
            {},
        ),
    }


def validate_job_checkpoint(
    job_name: str,
    timeout_seconds: float = 0,
    poll_interval_seconds: float = 30,
) -> dict:
    """Wait up to the timeout for an active job's first completed checkpoint."""
    if timeout_seconds < 0 or poll_interval_seconds <= 0:
        raise ValueError("Timeout must be nonnegative and poll interval positive.")

    deadline = time.monotonic() + timeout_seconds
    while True:
        job = find_job_by_name(job_name)

        if not job:
            raise RuntimeError(f"Flink job not found: {job_name}")

        if job.get("state") not in RUNNING_STATES:
            raise RuntimeError(f"{job_name} is {job.get('state')}")

        stats = checkpoint_statistics(job["jid"])
        if stats["completed"] >= 1:
            return {
                "job_name": job_name,
                "state": job.get("state"),
                **stats,
            }

        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise RuntimeError(
                f"{job_name} has no completed checkpoint after waiting up to "
                f"{timeout_seconds}s. Job ID: {job['jid']}; "
                f"state: {job.get('state')}; checkpoint statistics: {stats}"
            )
        logging.getLogger(__name__).info(
            "Waiting for %s checkpoint: state=%s, in_progress=%s, failed=%s; "
            "%.0fs remaining",
            job_name, job.get("state"), stats["in_progress"],
            stats["failed"], remaining,
        )
        time.sleep(min(poll_interval_seconds, remaining))
